version: '3.8'

networks:
  backend:
  frontend:

services:
  db-mySql-evento:
    image: mysql:latest
    container_name: "db-mySql-evento"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db-mySql-evento
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - frontend

  node-app:
    image: node:latest
    container_name: "node-app"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - backend
    depends_on:
      - db-mySql-evento
      - redis
    command: 
      - bash
      - "-c"
      - |
        npm start

volumes:
  mysql_data:
  redis_data:
